[build.environment]
NODE_VERSION = "16"
NEXT_USE_NETLIFY_EDGE = "true"

[context.alpha]
environment = { CHANNEL = "alpha" }

[context.beta]
environment = { CHANNEL = "beta" }

[dev]
framework = "#static"

[[edge_functions]]
function = "pages/api/card.png"
path = "/api/card.png"

[[edge_handlers]]
handler = "pages/api/card.png"
path = "/api/card.png"