[build]
command = "next build"
publish = ".next"

[build.environment]
NODE_VERSION = "16"

[context.alpha]
environment = { CHANNEL = "alpha" }

[context.beta]
environment = { CHANNEL = "beta" }

[dev]
command = "next dev"
autoLaunch = false
